### ISSUE TITLE
Bug when trying to put "01" in birth date

### ISSUE THREAD

**Issue by switowski** [pythonitalia/pycon_site#152]
Hi there,

I just tried to update the birth date in my profile to the most common one on the internet (01/01) but when I put the first 0, the form immediately crashes (see the attached gif)

![buginbirthdate](https://user-images.githubusercontent.com/4835412/70427272-b5fce600-1a74-11ea-959c-4dec5e5de665.gif)

**Comment by patrick91** [comment]
@switowski thanks for the report!

The new repo is here: I made a PR: https://github.com/pythonitalia/pycon/pull/1390 😊

**Comment by patrick91** [comment]
@switowski merged! I'll close this. I think in future we'll make the birth date optional, I need to check with the other organisers :)
